In [14]:
import soccerdata as sd

# sofifa.com serves pages in the browser's locale, and soccerdata's parsers only
# match English labels — on this machine every attribute came back None and the
# tactic columns came back in French. SoFIFAEn forces hl=en-US. See sofifa_en.py.
from sofifa_en import SoFIFAEn

In [15]:
sofifa = SoFIFAEn(leagues="ENG-Premier League", versions="latest")
sofifa.versions  # `update` should read "Jul 23, 2026", not "23 juil. 2026"

[07/27/26 14:20:08] INFO     Saving cached data to /Users/safidyramaherison/soccerdata/data/SoFIFA   ]8;id=11236026;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/.venv/lib/python3.14/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=11236027;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/.venv/lib/python3.14/site-packages/soccerdata/_common.py#250\250]8;;\

           fifa_edition        update
version_id
260046            FC 26  Jul 23, 2026

In [16]:
team_ratings = sofifa.read_team_ratings()
team_ratings.head()

[07/27/26 14:20:09] INFO     [1/1] Retrieving teams for ENG-Premier League in Jul 23, 2026 edition    ]8;id=11236032;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/.venv/lib/python3.14/site-packages/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=11236033;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/.venv/lib/python3.14/site-packages/soccerdata/sofifa.py#341\341]8;;\

                                          overall attack midfield defence  \
league             team
ENG-Premier League AFC Bournemouth             78     79       78      77
                   Arsenal                     84     86       85      84
                   Aston Villa                 81     82       81      80
                   Brentford                   78     81       78      77
                   Brighton & Hove Albion      78     80       79      78

                                          transfer_budget club_worth  \
league             team
ENG-Premier League AFC Bournemouth                 €63.3M      €410M
                   Arsenal                        €153.3M      €2.5B
                   Aston Villa                     €77.6M      €800M
                   Brentford                       €53.7M      €430M
                   Brighton & Hove Albion          €76.9M      €785M

                                          build_up_speed build_up_dribbling  \
league             team
ENG-Premier League AFC Bournemouth                  Slow             Little
                   Arsenal                          Slow             Little
                   Aston Villa                      Slow             Little
                   Brentford                        Slow             Little
                   Brighton & Hove Albion           Slow             Little

                                          build_up_passing  \
league             team
ENG-Premier League AFC Bournemouth                   Short
                   Arsenal                           Short
                   Aston Villa                       Short
                   Brentford                         Short
                   Brighton & Hove Albion            Short

                                          build_up_positioning  ...  \
league             team                                         ...
ENG-Premier League AFC Bournemouth                   Organised  ...
                   Arsenal                           Organised  ...
                   Aston Villa                       Organised  ...
                   Brentford                         Organised  ...
                   Brighton & Hove Albion            Organised  ...

                                          defence_pressure defence_team_width  \
league             team
ENG-Premier League AFC Bournemouth                    Deep             Narrow
                   Arsenal                            Deep             Narrow
                   Aston Villa                        Deep             Narrow
                   Brentford                          Deep             Narrow
                   Brighton & Hove Albion             Deep             Narrow

                                          defence_defender_line  \
league             team
ENG-Premier League AFC Bournemouth                        Cover
                   Arsenal                                Cover
                   Aston Villa                            Cover
                   Brentford                              Cover
                   Brighton & Hove Albion                 Cover

                                          defence_domestic_prestige  \
league             team
ENG-Premier League AFC Bournemouth                                4
                   Arsenal                                       10
                   Aston Villa                                    7
                   Brentford                                      3
                   Brighton & Hove Albion                         5

                                          international_prestige players  \
league             team
ENG-Premier League AFC Bournemouth                             4      28
                   Arsenal                                     9      23
                   Aston Villa                                 7      27
                   Brentford                                   3      26
                   Brighton & Hove Albion                      5      27

                                          starting_xi_average_age  \
league             team
ENG-Premier League AFC Bournemouth                          24.73
                   Arsenal                                  26.00
                   Aston Villa                              27.73
                   Brentford                                23.73
                   Brighton & Hove Albion                   26.09

                                          whole_team_average_age fifa_edition  \
league             team
ENG-Premier League AFC Bournemouth                         23.93        FC 26
                   Arsenal                                 25.74        FC 26
                   Aston Villa                             26.11        FC 26
                   Brentford                               24.15        FC 26
                   Brighton & Hove Albion                  25.15        FC 26

                                                 update
league             team
ENG-Premier League AFC Bournemouth         Jul 23, 2026
                   Arsenal                 Jul 23, 2026
                   Aston Villa             Jul 23, 2026
                   Brentford               Jul 23, 2026
                   Brighton & Hove Albion  Jul 23, 2026

[5 rows x 25 columns]

In [17]:
player_ratings = sofifa.read_player_ratings(team="Arsenal")
player_ratings.head()

                    INFO     [1/1] Retrieving teams for ENG-Premier League in Jul 23, 2026 edition    ]8;id=11236038;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/.venv/lib/python3.14/site-packages/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=11236039;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/.venv/lib/python3.14/site-packages/soccerdata/sofifa.py#188\188]8;;\

                    INFO     [1/1] Retrieving list of players for Arsenal in Jul 23, 2026 edition     ]8;id=11236044;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/.venv/lib/python3.14/site-packages/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=11236045;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/.venv/lib/python3.14/site-packages/soccerdata/sofifa.py#259\259]8;;\

                    INFO     [1/23] Retrieving ratings for player with ID 220901 in Jul 23, 2026   ]8;id=11236052;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236053;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [2/23] Retrieving ratings for player with ID 251805 in Jul 23, 2026   ]8;id=11236058;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236059;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [3/23] Retrieving ratings for player with ID 243715 in Jul 23, 2026   ]8;id=11236064;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236065;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [4/23] Retrieving ratings for player with ID 232580 in Jul 23, 2026   ]8;id=11236070;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236071;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [5/23] Retrieving ratings for player with ID 257711 in Jul 23, 2026   ]8;id=11236076;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236077;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [6/23] Retrieving ratings for player with ID 248148 in Jul 23, 2026   ]8;id=11236082;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236083;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [7/23] Retrieving ratings for player with ID 234378 in Jul 23, 2026   ]8;id=11236088;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236089;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [8/23] Retrieving ratings for player with ID 246669 in Jul 23, 2026   ]8;id=11236094;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236095;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [9/23] Retrieving ratings for player with ID 207421 in Jul 23, 2026   ]8;id=11236100;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236101;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [10/23] Retrieving ratings for player with ID 235794 in Jul 23, 2026  ]8;id=11236106;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236107;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [11/23] Retrieving ratings for player with ID 241651 in Jul 23, 2026  ]8;id=11236112;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236113;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [12/23] Retrieving ratings for player with ID 251566 in Jul 23, 2026  ]8;id=11236118;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236119;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [13/23] Retrieving ratings for player with ID 254796 in Jul 23, 2026  ]8;id=11236124;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236125;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [14/23] Retrieving ratings for player with ID 222665 in Jul 23, 2026  ]8;id=11236130;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236131;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [15/23] Retrieving ratings for player with ID 210697 in Jul 23, 2026  ]8;id=11236136;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236137;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

[07/27/26 14:20:10] INFO     [16/23] Retrieving ratings for player with ID 256197 in Jul 23, 2026  ]8;id=11236142;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236143;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [17/23] Retrieving ratings for player with ID 231936 in Jul 23, 2026  ]8;id=11236148;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236149;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [18/23] Retrieving ratings for player with ID 206585 in Jul 23, 2026  ]8;id=11236154;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236155;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [19/23] Retrieving ratings for player with ID 235790 in Jul 23, 2026  ]8;id=11236160;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236161;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [20/23] Retrieving ratings for player with ID 230666 in Jul 23, 2026  ]8;id=11236166;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236167;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [21/23] Retrieving ratings for player with ID 264846 in Jul 23, 2026  ]8;id=11236172;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236173;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [22/23] Retrieving ratings for player with ID 278773 in Jul 23, 2026  ]8;id=11236178;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236179;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

                    INFO     [23/23] Retrieving ratings for player with ID 225193 in Jul 23, 2026  ]8;id=11236184;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py\sofifa_en.py]8;;\:]8;id=11236185;file:///Users/safidyramaherison/Documents/Jedha/AIFS/Projects/Final_project/Futbol/sofifa_en.py#174\174]8;;\
                             edition

,fifa_edition,update,overallrating,potential,crossing,finishing,headingaccuracy,shortpassing,volleys,dribbling,...,penalties,composure,defensiveawareness,standingtackle,slidingtackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player,,,,,,,,,,,,,,,,,,,,,
Benjamin William White,FC 26,"Jul 23, 2026",82,82,77,30,78,80,23,74,...,24,81,82,83,81,8,11,12,5,6
Bukayo Saka,FC 26,"Jul 23, 2026",87,89,90,82,49,85,79,86,...,87,82,60,62,60,7,8,13,9,13
Christian Thers Barsøe Nørgaard,FC 26,"Jul 23, 2026",80,80,68,63,69,79,51,69,...,62,77,77,80,79,11,9,13,14,11
Chukwunonso Azuka Tristan Madueke,FC 26,"Jul 23, 2026",80,84,74,75,55,76,65,85,...,75,80,45,45,30,5,13,6,12,15
Cristhian Andrey Mosquera Ibarguen,FC 26,"Jul 23, 2026",77,85,44,39,77,73,29,40,...,49,69,77,80,76,8,6,13,8,7